name: Python Flask CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest

      - name: Run tests
        run: |
          pytest

  test-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test job
        run: echo "Running test job..."

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: deply using ssh
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.HOST_IP }}"
          username: "${{ secrets.HOST_USER }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          command_timeout: 30m
          script: |
            cd ${{ secrets.DEPLOY_DIR }}
            echo "Discard server changes..."
            git stash
            echo "Pull new codebase..."
            git pull origin
            echo "Build and deploy docker container..."
            docker compose up --build --remove-orphans -d
            echo "Server cleanup..."
            yes | docker image prune
